# You can use `_TAMBO_PATH_` and it will be replaced by the path to the Tambo source directory

[steering]
nevent = 100
seed = 925
run_number = 925

[geometry]
geo_spline_path = "_TAMBO_PATH_/../../resources/tambo_spline.jld2"
tambo_coordinates = [-15.63863, -72.16498] # [latitude, longitude], degrees, calculated for the whitepaper location
plane_orientation = [0.452174, -0.366163, 0.813304] # calculated for the whitepaper location
