# You can use `_TAMBO_PATH_` and it will be replaced by the path to the Tambo source directory

[corsika]

parallelize_corsika = false
batch_submit_corsika = true
thinning = 1e-6
hadron_ecut = 0.05 # GeV
em_ecut = 0.001 # GeV

photon_ecut = 0.001 # GeV
mu_ecut = 0.05 # GeV
shower_dir = "showers/"
singularity_path = "/n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/source/corsika8/corsika-env.simg"
corsika_path = "/n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/source/corsika8/corsika-work/corsika"
corsika_sbatch_path = "/n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/source/TAMBO-MC/scripts/corsika_parallel.sbatch"
