# You can use `_TAMBO_PATH_` and it will be replaced by the path to the Tambo source directory

[steering]
nevent = 100
seed = 925
run_number = 925

[geometry]
geo_spline_path = "_TAMBO_PATH_/../../resources/tambo_spline.jld2"
tambo_coordinates = [-15.63863, -72.16498] # [latitude, longitude], degrees, calculated for the whitepaper location
plane_orientation = [0.452174, -0.366163, 0.813304] # calculated for the whitepaper location

[injection]

nu_pdg = 16
gamma = 1
emin = 1e6 # GeV
emax = 1e9 # GeV
thetamin = 0.0 # degrees
thetamax = 180.0 # degrees
phimin = 0.0 # degrees
phimax = 360.0 # degrees
r_injection = 2000.0 # m
l_endcap = 1000.0 # m
xs_dir = "_TAMBO_PATH_/../../resources/cross_sections/tables/"
xs_model = "csms"
interaction = "CC"

[proposal]
ecut = -1 # GeV. Negative <-> Infinity
vcut = 1e-2
do_interpolate = true
do_continuous = true
tablespath = "_TAMBO_PATH_/../..//resources/proposal_tables/"

[corsika]

parallelize_corsika = false
batch_submit_corsika = true
thinning = 1e-6
hadron_ecut = 0.05 # GeV
em_ecut = 0.001 # GeV

photon_ecut = 0.001 # GeV
mu_ecut = 0.05 # GeV
shower_dir = "showers/"
singularity_path = "/n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/source/corsika8/corsika-env.simg"
corsika_path = "/n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/source/corsika8/corsika-work/corsika"
corsika_sbatch_path = "/n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/source/TAMBO-MC/scripts/corsika_parallel.sbatch"
