# You can use `_TAMBO_PATH_` and it will be replaced by the path to the Tambo source directory

[injection]

nu_pdg = 16
gamma = 1
emin = 1e6 # GeV
emax = 1e9 # GeV
thetamin = 0.0 # degrees
thetamax = 180.0 # degrees
phimin = 0.0 # degrees
phimax = 360.0 # degrees
r_injection = 2000.0 # m
l_endcap = 1000.0 # m
xs_dir = "_TAMBO_PATH_/../../resources/cross_sections/tables/"
xs_model = "csms"
interaction = "CC"
