[steering]
nevent = 20000
pinecone = 0
run_number = 0

[geometry]
geo_spline_path = "_TAMBOSIM_PATH_/resources/perfect_valley_spline.jld2"
tambo_coordinates = [0.0, -0.015738128103577786] # Latitude, Longitude in degrees of detector array center
plane_orientation = [0.5655283556, 0, 0.8247288518]

[injection]
nu_pdg = 16
gamma = 2.0
emin = 3.0e5 # GeV
emax = 1.0e9
thetamin = 0 # degrees
thetamax = 117 # degrees
phimin = 90 # degrees
phimax = 270 # degrees
r_injection = 2000.0 # m
l_endcap = 1000.0 # m
xs_dir = "_TAMBOSIM_PATH_/resources/cross_sections/tables/"
xs_model = "csms"
interaction = "CC"
track_progress = false

[proposal]
ecut = -1 # GeV. Negative <-> Infinity
vcut = 1e-2
do_interpolate = true
do_continuous = true
tablespath = "_TAMBOSIM_PATH_/resources/proposal_tables/"
track_progress = false

[corsika]
should_run_corsika = false
parallelize_corsika = false
thinning = 1.0e-6
hadron_ecut = 0.05 # GeV
em_ecut = 0.001 # GeV
photon_ecut = 0.001 # GeV
mu_ecut = 0.05 # GeV
corsika_path = "/n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/source/corsika8/corsika-install/bin/c8_air_shower"
track_progress = false
FLUPRO = "/n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/source/fluka"
FLUFOR = "gfortransbatch"
