# You can use `_TAMBO_PATH_` and it will be replaced by the path to the Tambo source directory

[proposal]
ecut = -1 # GeV. Negative <-> Infinity
vcut = 1e-2
do_interpolate = true
do_continuous = true
tablespath = "_TAMBO_PATH_/../..//resources/proposal_tables/"
