[steering]
nevent = 500
pinecone = 1313
run_number = 666

[geometry]
geo_spline_path = "/n/home02/thomwg11/tambo/TAMBO-MC/resources/perfect_valley_spline.jld2"
tambo_coordinates = [0.0, -0.015738128103577786] # Latitude, Longitude in degrees such that center of spline is at (0,0)
plane_orientation = [0.5655283556, 0, 0.8247288518]

[injection]
nu_pdg = 16
gamma = 2.0
emin = 3.0e5 # GeV
emax = 1.0e8
thetamin = 60 # degrees
thetamax = 117 # degrees
phimin = 90 # degrees
phimax = 270 # degrees
r_injection = 2000.0 # m
l_endcap = 1000.0 # m
xs_dir = "/n/home02/thomwg11/tambo/TAMBO-MC/resources/cross_sections/tables/"
xs_model = "csms"
interaction = "CC"
track_progress = true

[proposal]
ecut = -1 # GeV. Negative <-> Infinity
vcut = 1e-2
do_interpolate = true
do_continuous = true
tablespath = "/n/home02/thomwg11/tambo/TAMBO-MC/resources/proposal_tables/"
track_progress = false

[corsika]
should_run_corsika = false
parallelize_corsika = false
#batch_submit_corsika = true
thinning = 0.0
hadron_ecut = 0.05 # GeV
em_ecut = 0.001 # GeV
photon_ecut = 0.001 # GeV
mu_ecut = 0.05 # GeV
corsika_path = "/n/holylfs05/LABS/arguelles_delgado_lab/Lab/common_software/source/corsika8/corsika-install/bin/c8_air_shower"
track_progress = false
