[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
FHist = "68837c9b-b678-4cd5-9925-8a54edc8f695"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SmoothingSplines = "102930c3-cf33-599f-b3b1-9a29a5acab30"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tambo = "d9a96183-4919-46da-8188-64ea4e10e0ed"
