name = "tambo"
uuid = "d9a96183-4919-46da-8188-64ea4e10e0ed"
authors = ["Carlos A. Arguelles <carguelles@fas.harvard.edu>"]
version = "0.1.0"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
