name = "Tambo"
uuid = "d9a96183-4919-46da-8188-64ea4e10e0ed"
authors = ["Carlos A. Arguelles <carguelles@fas.harvard.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaturallyUnitful = "872cf16e-200e-11e9-2cdf-8bb39cfbec41"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
